### PR TITLE
feat : express flash module added for flash message

### PR DESCRIPTION
**Pull request by Nadeera3784**

### CODE REVIEW

**Comment by Katheesh** [comment]
@Nadeera3784 if You will joint our discord group I add as a member to @**opshit** organization.
thanks. best regards.

**Comment by Katheesh** [comment]
@Nadeera3784 Check this issue: https://github.com/opshit/opshit/issues/16

**Comment by Nadeera3784** [comment]
Why did you put language.js helper inside the config folder ? it should be in the helper folder.

**Comment by Katheesh** [comment]
We need to follow folder structure like laravel. no additional folder need outside. hope you understand.

**Comment by Nadeera3784** [comment]
that's not good. stop imitating others. we should create our own folder structure.

**Comment by Katheesh** [comment]
We followed standard folder structure. we already planned on documentation. [https://opshit.netlify.app/docs/Getting%20Started.html#structure-of-folder-tree](https://opshit.netlify.app/docs/Getting%20Started.html#structure-of-folder-tree)

**Pull request merged**
