### PR TITLE
feat : helmet module added for extra security

### PR DESCRIPTION
**Pull request by Nadeera3784**
helmet module added for extra security

### CODE REVIEW

**Comment by i2z** [comment]
Opshit has several issues. can you solve some issues?

**Comment by Nadeera3784** [comment]
Yeah sure.

**Comment by Nadeera3784** [comment]
can't we rename the name of this ? from opshit to something else, something fancy.

**Comment by i2z** [comment]
Yeah sure we'll discuss about that. join our discord we can discuss our group. thanks.

[https://discord.gg/rN8FBU](https://discord.gg/rN8FBU)

**Comment by Nadeera3784** [comment]
How about using Slack .

**Comment by i2z** [comment]
Slack is good but most of opshit team using discord. so if you can install we'll discuss something new.

**Pull request merged**
